export const SIGN_IN_FORM_EMAIL_CHANGE = 'SIGN_IN_FORM_EMAIL_CHANGE'
export const SIGN_IN_FORM_PASSWORD_CHANGE = 'SIGN_IN_FORM_PASSWORD_CHANGE'
export const SIGN_IN_FORM_VALIDATION_MESSAGES_VISIBLE
  = 'SIGN_IN_FORM_VALIDATION_MESSAGES_VISIBLE'
export const SIGN_IN_FORM_ERROR = 'SIGN_IN_FORM_ERROR'
export const SIGN_IN_FORM_DISABLED = 'SIGN_IN_FORM_DISABLED'
export const SIGN_IN_FORM_RESET = 'SIGN_IN_FORM_RESET'
