export const USER_FORM_INIT = 'USER_FORM_INIT';
export const USER_FORM_EMAIL_CHANGE = 'USER_FORM_EMAIL_CHANGE';
export const USER_FORM_VALIDATION_MESSAGES_VISIBLE
  = 'USER_FORM_VALIDATION_MESSAGES_VISIBLE';
export const USER_FORM_ERROR = 'USER_FORM_ERROR';
export const USER_FORM_DISABLED = 'USER_FORM_DISABLED';
